version: '3.9'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: backendtemplate-webapi:latest
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=sereq;Username=postgres;Password=admin
      - Jwt__Key=local-development-key-change-in-production-2026
      - Jwt__Issuer=EA
      - Jwt__Audience=EA.Admin
      - Jwt__SidKey=local-development-sid-encryption-key-change-in-production-2026
      - Admin__Login=admin
      - Admin__Password=admin
